services:
  protobuf-generator-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: marcel-kerth/protobuf-generator
    volumes:
      - ../../src:/src
    working_dir: "/root"
    command: ["bash", "/src/app/build/run.bash"]